using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RinkuNomina.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class Idsautogeneratedtables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<Guid>(
                name: "IdTipoBono",
                table: "TipoBono",
                type: "uniqueidentifier",
                nullable: false,
                defaultValueSql: "NEWSEQUENTIALID()",
                comment: "Llave principal de la tabla",
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdSueldoBase",
                table: "SueldoBase",
                type: "uniqueidentifier",
                nullable: false,
                defaultValueSql: "NEWSEQUENTIALID()",
                comment: "Llave principal de la tabla",
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdRol",
                table: "RolEmpleado",
                type: "uniqueidentifier",
                nullable: false,
                defaultValueSql: "NEWSEQUENTIALID()",
                comment: "Llave principal de la tabla",
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdFrecuenciaBono",
                table: "FrecuenciaBono",
                type: "uniqueidentifier",
                nullable: false,
                defaultValueSql: "NEWSEQUENTIALID()",
                comment: "Llave principal de la tabla",
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdEntrega",
                table: "EntregasPorEmpleado",
                type: "uniqueidentifier",
                nullable: false,
                defaultValueSql: "NEWSEQUENTIALID()",
                comment: "Llave principal de la tabla",
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdEmpleado",
                table: "Empleado",
                type: "uniqueidentifier",
                nullable: false,
                defaultValueSql: "NEWSEQUENTIALID()",
                comment: "Llave principal de la tabla",
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdCliente",
                table: "Cliente",
                type: "uniqueidentifier",
                nullable: false,
                defaultValueSql: "NEWSEQUENTIALID()",
                comment: "Llave principal de la tabla",
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdBonoRol",
                table: "BonosPorRol",
                type: "uniqueidentifier",
                nullable: false,
                defaultValueSql: "NEWSEQUENTIALID()",
                comment: "Llave principal de la tabla",
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdBitacoraSueldo",
                table: "BitacoraSueldo",
                type: "uniqueidentifier",
                nullable: false,
                defaultValueSql: "NEWSEQUENTIALID()",
                comment: "Llave principal de la tabla",
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<Guid>(
                name: "IdTipoBono",
                table: "TipoBono",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldDefaultValueSql: "NEWSEQUENTIALID()",
                oldComment: "Llave principal de la tabla");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdSueldoBase",
                table: "SueldoBase",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldDefaultValueSql: "NEWSEQUENTIALID()",
                oldComment: "Llave principal de la tabla");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdRol",
                table: "RolEmpleado",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldDefaultValueSql: "NEWSEQUENTIALID()",
                oldComment: "Llave principal de la tabla");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdFrecuenciaBono",
                table: "FrecuenciaBono",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldDefaultValueSql: "NEWSEQUENTIALID()",
                oldComment: "Llave principal de la tabla");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdEntrega",
                table: "EntregasPorEmpleado",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldDefaultValueSql: "NEWSEQUENTIALID()",
                oldComment: "Llave principal de la tabla");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdEmpleado",
                table: "Empleado",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldDefaultValueSql: "NEWSEQUENTIALID()",
                oldComment: "Llave principal de la tabla");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdCliente",
                table: "Cliente",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldDefaultValueSql: "NEWSEQUENTIALID()",
                oldComment: "Llave principal de la tabla");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdBonoRol",
                table: "BonosPorRol",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldDefaultValueSql: "NEWSEQUENTIALID()",
                oldComment: "Llave principal de la tabla");

            migrationBuilder.AlterColumn<Guid>(
                name: "IdBitacoraSueldo",
                table: "BitacoraSueldo",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldDefaultValueSql: "NEWSEQUENTIALID()",
                oldComment: "Llave principal de la tabla");
        }
    }
}
